title: Guitar Theory
description: Quelques notes ...

markdown: kramdown

sass:
  style: :compressed

lang: fr-FR
encoding: UTF-8
branch: master

collections_dir: collections

collections:
  theorie:
      output: true
      permalink: /theorie/:path/
  rythme:
      output: true
      permalink: /rythme/:path/
  tips:
      output: true
      permalink: /tips/:path/
  exercices:
      output: true
      permalink: /exercices/:path/
  modes:
      output: true
      permalink: /modes/:path/
  scales:
      output: true
      permalink: /scales/:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      pdf: true

mermaid: true

excerpt_separator: <!--more-->

nav_pages:
  - pages/posts.md
  - pages/theorie.md
  - pages/scales.md
  - pages/modes.md
  - pages/rythme.md
  - pages/exercices.md
  - pages/tips.md
  - pages/ressources.md

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - .editorconfig
  - .gitignore
  - package.json
  - package-lock.json

theme: null
