title: Musique
description: Quelques notes ...

markdown: kramdown

sass:
  style: :compressed

lang: fr-FR
encoding: UTF-8
branch: master

collections_dir: collections

collections:
  theorie:
      output: true
      permalink: /theorie/:path/
  rythme:
      output: true
      permalink: /rythme/:path/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

mermaid: true

nav_pages:
  - theorie.md
  - ressources.md

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md

theme: null
