title: Musique
description: Quelques notes ...

markdown: kramdown

sass:
  style: :compressed

lang: fr-FR
encoding: UTF-8
branch: master

collections_dir: collections

collections:
  theorie:
      output: true
      permalink: /theorie/:path/
  rythme:
      output: true
      permalink: /rythme/:path/
  tips:
      output: true
      permalink: /tips/:path/
  exercices:
      output: true
      permalink: /exercices/:path/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      pdf: true

mermaid: true

nav_pages:
  - collections/theorie.md
  - collections/rythme.md
  - collections/exercices.md
  - collections/tips.md
  - collections/ressources.md

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md

theme: null
