title: Musique
description: Quelques notes ...

markdown: kramdown

sass:
  style: :compressed

lang: fr-FR
encoding: UTF-8
branch: master

collections_dir: collections

collections:
  theorie:
      output: true
      permalink: /theorie/:path/

nav_pages:
  - theorie.md
  - ressources.md

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md

theme: null